module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
    - source: static
      target: static

params:
  realestates:
    thumbnail:
      desktop: "416x291"
      mobile: "300x210"
      scrollsnap: "240x168"
    image:
      desktop: "850x"
      mobile: "300x"

# Default
permalinks:
  realestates: /realestates/:slug/